auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            Vigoals的博客
url:              http://vigoals.github.com
feed:             /atom.xml
author:
    name:         Vigoals
description:      "BeiYuu\'s Blog"
author_info:      <a href="http://vigoals.github.com">Vigoals</a>

copyright:
    - Design by <a href="http://vigoals.github.com" title="Vigoals" target="_blank">Vigoals</a> &copy; Copyright 2012
